#!/bin/bash

#PBS -N Wyckoff_Training

#PBS -l select=1:ncpus=8:mem=46gb:ngpus=1

#PBS -l walltime=24:00:00

#PBS -M z5561341@ad.unsw.edu.au

#PBS -m ae

#PBS -j oe

cd /srv/scratch/z5561341/projectA/cdvae/cdvae
source /srv/scratch/z5561341/miniconda3/bin/activate
conda activate cdvae
WANDB_API_KEY="" WANDB_MODE=disabled python run.py data=mp_20 model=wyckoff_cdvae expname=test_wyckoff logging.wandb.mode=disabled