#!/bin/bash

#PBS -N SMACT_filter

#PBS -l select=1:ncpus=8:mem=46gb:ngpus=0

#PBS -l walltime=12:00:00

#PBS -M z5561341@ad.unsw.edu.au

#PBS -m ae

#PBS -j oe
SCRATCH=/srv/scratch/ml4matdis/Quanli_Project/z5561341
SCRIPTS=$SCRATCH/projectA/cdvae/scripts
INPUT=$SCRATCH/generated_structures/cfg_0
OUTPUT=$SCRATCH/SMACT_structure/cfg_0

cd /srv/scratch/ml4matdis/Quanli_Project/z5561341/projectA/cdvae/cdvae
source /srv/scratch/z5561341/miniconda3/bin/activate
conda activate cdvae
python $SCRIPTS/smact_filter.py \
    --input_dir  $INPUT  \
    --output_dir $OUTPUT \
   