#!/bin/bash

#PBS -N Generating

#PBS -l select=1:ncpus=8:mem=46gb:ngpus=0

#PBS -l walltime=12:00:00

#PBS -M z5561341@ad.unsw.edu.au

#PBS -m ae

#PBS -j oe

cd /srv/scratch/ml4matdis/Quanli_Project/z5561341/projectA/cdvae/cdvae
source /srv/scratch/z5561341/miniconda3/bin/activate
conda activate cdvae2
python /srv/scratch/ml4matdis/Quanli_Project/z5561341/projectA/cdvae/scripts/generate_wyckoff.py 