#!/bin/bash

#PBS -N Generating

#PBS -l select=1:ncpus=8:mem=46gb:ngpus=0

#PBS -l walltime=12:00:00

#PBS -M z5561341@ad.unsw.edu.au

#PBS -m ae

#PBS -j oe
SCRATCH=/srv/scratch/ml4matdis/Quanli_Project/z5561341
OUTPUT=$SCRATCH/generated_structures/formal_structure
OUTPUT_CFG0=$SCRATCH/generated_structures/cfg_0
OUTPUT_CFG2=$SCRATCH/generated_structures/cfg_2
OUTPUT_CFG4=$SCRATCH/generated_structures/cfg_4
OUTPUT_test=$SCRATCH/generated_structures/cfg_Oxi


cd /srv/scratch/ml4matdis/Quanli_Project/z5561341/projectA/cdvae/cdvae
source /srv/scratch/z5561341/miniconda3/bin/activate
conda activate cdvae2
python /srv/scratch/ml4matdis/Quanli_Project/z5561341/projectA/cdvae/scripts/generate_wyckoff.py \
   --out_dir $OUTPUT \
   --num_samples 2500 \
   --stability_class 0 \
   --cfg_w 0.0
#   --target_elements "Ba,Ti,O" \
#   --must_contain all

